### ISSUE TITLE
Left some test code behind.

### ISSUE THREAD

**Issue by jarrodconnolly** [pricelessbrewing/pricelessbrewing.github.io#1]
The BrewName field pops up a TestingTesting dialog when clicked.

`<div class="control-group" onclick="alert('TestingTesting');">
`
https://github.com/pricelessbrewing/pricelessbrewing.github.io/blob/ef9eb6bb7c0e51677704929294a9b6051f507a29/BiabCalc/index.html#L66

**Comment by pricelessbrewing** [comment]
Woops, thanks!
